version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - PORT=8001
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço opcional para desenvolvimento com hot-reload
  app-dev:
    build: .
    ports:
      - "8002:8001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - PORT=8001
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./backups:/app/backups
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8001", "--reload"]
    profiles:
      - dev

  # Serviço para testes
  app-test:
    build: .
    environment:
      - FLASK_ENV=testing
      - FLASK_DEBUG=False
      - PORT=8001
    volumes:
      - .:/app
    command: ["python", "-m", "pytest", "tests/", "-v"]
    profiles:
      - test

networks:
  default:
    name: projet-veloz-network 